version: '3'
services:
  web:   
      image: nginx:latest  
      container_name: nginx-container  
      ports:	
        - ${NGINX_SERVER_PORT}:80 
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./logs/nginx:/var/log/nginx
        - ${PROJECT_PATH}:/app
  
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./logs/php:/var/log/php
      - ${PROJECT_PATH}:/app
    
  composer:
    image: composer:1.8
    #command: ["composer", "install"]
    volumes:
      - ${PROJECT_PATH}:/app
       
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    # restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
      
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URL}
      - ME_CONFIG_BASICAUTH_USERNAME=${MEXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MEXPRESS_PASSWORD}
    # depends_on:
    #   - mongo
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"  

